Main:
	prob
	
a:
	g++ probA.cpp -o prob
	prob
b:
	g++ probB.cpp -o prob
	prob
c:
	g++ probC.cpp -o prob
	prob
d:
	g++ probD.cpp -o prob
	prob
e:
	g++ probE.cpp -o prob
	prob
f:
	g++ probF.cpp -o prob
	prob
g:
	g++ probG.cpp -o prob
	prob
	
	
